spring:
  application:
    name: UserSociableSphere

  r2dbc:
    url: r2dbc:mysql://ugv3eam0kly3dszy:esHA6Jl0UbfDSWGatObJ@b4kifbvseeho1hfhwmeq-mysql.services.clever-cloud.com:3306/b4kifbvseeho1hfhwmeq
    username: ugv3eam0kly3dszy
    password: esHA6Jl0UbfDSWGatObJ

  data:
    r2dbc:
      repositories:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
