spring:
  application:
    name: UserSociableSphere

  security:
    user:
      name: user
      password: user

  r2dbc:
    url: r2dbc:mysql://localhost:3306/UsersSocialSphere
    username: users
    password: users

  h2:
    console:
      enabled: true
      path: /h2-console
